name: gdd
description: "Aplicación para confirmar o registrar devoluciones en los despachos directos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  http: ^1.3.0
  gif: ^2.3.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  geolocator: ^14.0.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "gdd_icon"
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon-background.png"
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_foreground_inset: 4

flutter:
  uses-material-design: true

  assets:
    - assets/ending.gif
    - assets/login.png
    - assets/logo.png
    - assets/logo2.png
    - assets/sound.mp3
    - assets/chofer.iancarina.com.ve.crt