name: driver_return
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_expandable_fab: ^2.4.1
  local_auth: ^2.3.0
  provider: ^6.1.4
  http: ^1.3.0
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ending.gif
    - assets/login.png
    - assets/logo.png